"use strict";
const SUPABASE_BASE="https://hzjsatehehhpgpskckfi.supabase.co";
const SUPABASE_KEY="sb_publishable_5swzjbs4yq7N8sDNR00FHA_n1xbnMya";
const $=id=>document.getElementById(id),names={bunner:"Bunner",hyller30:"Hyller x30",hyller60:"Hyller x60"},statusNames={new:"Ny",received:"Mottatt",in_progress:"Pågår",staged:"På rampe",problem:"Problem",completed:"Ferdig",cancelled:"Stornert"};
let state={product:"bunner",mode:"stacks",stacks:1,total:10,direct:1},orders=[],busy=false,editingId=null;
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function headers(extra={}){return{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`,Accept:"application/json","Content-Type":"application/json",...extra}}
async function request(path,options={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);try{const response=await fetch(`${SUPABASE_BASE}/rest/v1/${path}`,{...options,headers:headers(options.headers||{}),signal:controller.signal});const text=await response.text();let body=null;if(text){try{body=JSON.parse(text)}catch{body=text}}if(!response.ok){const message=body&&typeof body==="object"?(body.message||body.hint||body.details||`HTTP ${response.status}`):(body||`HTTP ${response.status}`);throw new Error(message)}return body}catch(error){if(error.name==="AbortError")throw new Error("Ingen svar fra Supabase innen 15 sekunder.");throw error}finally{clearTimeout(timer)}}
function setConnection(prefix,text,type="",detail=""){$(`${prefix}Status`).textContent=text;$(`${prefix}Dot`).className=`dot ${type}`.trim();const box=$(`${prefix}Error`);box.textContent=detail;box.classList.toggle("show",Boolean(detail))}
function count(rows,p,s){return rows.filter(r=>r.product===p&&r.status===s).length}
async function loadInn(){setConnection("inn","Lagerstatus…");try{const rows=await request("mottak_scans?select=product,status&limit=10000")||[];const b=count(rows,"bunner","verified"),h30=count(rows,"hyller30","verified"),h60=count(rows,"hyller60","verified"),pb=count(rows,"bunner","pending"),p30=count(rows,"hyller30","pending"),p60=count(rows,"hyller60","pending");$("bunnerValue").textContent=`${b} ${b===1?"stabel":"stabler"} × 10 = ${b*10} stk.`;$("h30Value").textContent=`${h30} Bunner × 30 = ${h30*30} hyller`;$("h60Value").textContent=`${h60} Bunner × 60 = ${h60*60} hyller`;$("totalValue").textContent=`${b*10+h30+h60} Bunner · ${h30*30+h60*60} hyller`;$("pendingValue").textContent=`Pending: ${pb} Bunner · ${p30} Hyller x30 · ${p60} Hyller x60`;$("stockSummary").textContent=`${b*10+h30+h60} Bunner · ${h30*30+h60*60} hyller`;setConnection("inn","Lager tilkoblet","ok")}catch(e){$("stockSummary").textContent="Feil";setConnection("inn","Lagerfeil","bad",`Feil ved lesing av mottak_scans:\n${e.message||e}`)}}
function pos(v,f=1){v=parseInt(v,10);return Number.isFinite(v)&&v>0?v:f}function msg(t,c=""){$("message").textContent=t;$("message").className=`message ${c}`.trim()}function date(v){return new Intl.DateTimeFormat("nb-NO",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(v))}function orderNumber(){const d=new Date(),p=n=>String(n).padStart(2,"0");return `UT-${d.getFullYear()}${p(d.getMonth()+1)}${p(d.getDate())}-${p(d.getHours())}${p(d.getMinutes())}${p(d.getSeconds())}-${Math.random().toString(36).slice(2,6).toUpperCase()}`}function stackText(n){return `${n} ${n===1?"stabel":"stabler"} × 10 = ${n*10} Bunner`}
function quick(){const a=state.mode==="stacks"?[1,3,6,10]:[10,30,60,100];$("bQuick").innerHTML=a.map(v=>`<button data-q="${v}">${v}</button>`).join("");document.querySelectorAll("[data-q]").forEach(b=>b.onclick=()=>{const v=pos(b.dataset.q);if(state.mode==="stacks"){state.stacks=v;state.total=v*10}else{state.total=v;state.stacks=v/10}$("qty").value=v;render()})}
function mode(m){state.mode=m;document.querySelectorAll("[data-mode]").forEach(b=>b.classList.toggle("active",b.dataset.mode===m));if(m==="stacks"){state.stacks=Math.max(1,Math.round(state.total/10));state.total=state.stacks*10;$("qtyLabel").textContent="Antall stabler";$("qty").step=1;$("qty").value=state.stacks}else{state.total=Math.max(10,state.stacks*10);$("qtyLabel").textContent="Totalt antall Bunner";$("qty").step=10;$("qty").value=state.total}quick();render()}
function product(p){state.product=p;document.querySelectorAll("[data-product]").forEach(b=>b.classList.toggle("active",b.dataset.product===p));$("bunnerPanel").classList.toggle("hidden",p!=="bunner");$("directPanel").classList.toggle("hidden",p==="bunner");if(p!=="bunner")$("directLabel").textContent=`Antall ${names[p]}-sett`;msg("");render()}
function updateQty(){if(state.mode==="stacks"){state.stacks=pos($("qty").value);state.total=state.stacks*10;$("qty").value=state.stacks}else{state.total=pos($("qty").value,10);state.stacks=state.total/10;$("qty").value=state.total}render()}
function render(){const r=$("ramp").value.trim();$("sumRamp").textContent=r||"Ikke valgt";$("sumProduct").textContent=names[state.product];if(state.product==="bunner"){$("calc").textContent=`${state.total/10} × 10 = ${state.total} Bunner`;$("sumQty").textContent=stackText(state.total/10)}else $("sumQty").textContent=`${state.direct} sett ${names[state.product]}`}
function writePayload(includeCreate=false){const p={ramp:$("ramp").value.trim(),bunner_stacks:0,hyller30_sets:0,hyller60_sets:0,office_note:$("officeNote").value.trim()||null,updated_at:new Date().toISOString()};if(state.product==="bunner")p.bunner_stacks=state.total/10;if(state.product==="hyller30")p.hyller30_sets=state.direct;if(state.product==="hyller60")p.hyller60_sets=state.direct;if(includeCreate)Object.assign(p,{order_number:orderNumber(),status:"new",created_by:"office-web"});return p}
async function send(){if(!$("ramp").value.trim()){msg("Skriv inn rampenummer.","bad");$("ramp").focus();return}if(state.product==="bunner"&&state.total%10){msg("Totalt antall Bunner må være delelig med 10.","bad");return}if(busy)return;busy=true;$("send").disabled=true;$("receipt").classList.remove("show");try{if(editingId){msg("Lagrer endringer…");const rows=await request(`ut_orders?id=eq.${encodeURIComponent(editingId)}&status=eq.new`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify(writePayload(false))});const row=Array.isArray(rows)?rows[0]:rows;if(!row)throw new Error("Oppdraget er ikke lenger Ny og kan ikke redigeres.");msg("Endringene er lagret.","ok");clearForm(false)}else{msg("Sender UT-oppdrag…");const rows=await request("ut_orders",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify(writePayload(true))});const row=Array.isArray(rows)?rows[0]:rows;if(!row)throw new Error("Supabase returnerte ingen opprettet rad.");$("receiptNo").textContent=`${row.order_number} er sendt`;$("receiptText").textContent=`Oppdrag for rampe ${row.ramp} er sendt til lageret.`;$("receipt").classList.add("show");msg("UT-oppdraget er sendt.","ok")}await loadUt()}catch(e){msg(`${editingId?"Kunne ikke lagre endringer":"Kunne ikke sende UT-oppdrag"}.\n${e.message||e}`,"bad")}finally{busy=false;$("send").disabled=false}}
function amount(o){const b=+o.bunner_stacks||0,h30=+o.hyller30_sets||0,h60=+o.hyller60_sets||0,a=[];if(b)a.push(`${b} ${b===1?"stabel":"stabler"} × 10 = ${b*10} Bunner`);if(h30)a.push(`${h30} Hyller x30-sett = ${h30} Bunner + ${h30*30} hyller`);if(h60)a.push(`${h60} Hyller x60-sett = ${h60} Bunner + ${h60*60} hyller`);return a.join(" · ")||"Ingen varer"}
function singleProduct(o){const list=[];if(+o.bunner_stacks>0)list.push("bunner");if(+o.hyller30_sets>0)list.push("hyller30");if(+o.hyller60_sets>0)list.push("hyller60");return list.length===1?list[0]:null}
function activeOrders(){return orders.filter(o=>!["completed","cancelled"].includes(o.status))}
function renderHistory(){const active=activeOrders();if(!active.length){$("history").innerHTML='<div class="empty">Ingen aktive UT-oppdrag.</div>';$("historyCount").textContent="0";return}$("historyCount").textContent=String(active.length);$("history").innerHTML=active.slice(0,20).map(o=>{const s=statusNames[o.status]?o.status:"new",canEdit=s==="new"&&singleProduct(o);return `<article class="order ${s}"><div class="order-top"><div><div class="order-number">${esc(o.order_number||o.id)}</div><div class="ramp-title">RAMPE ${esc(o.ramp)}</div></div><span class="pill ${s}">${esc(statusNames[s])}</span></div><div class="amount">${esc(amount(o))}</div><div class="meta">${date(o.created_at)}${o.office_note?` · ${esc(o.office_note)}`:""}</div><div class="order-actions">${canEdit?`<button class="order-action edit-action" data-edit="${esc(o.id)}">Rediger</button>`:""}<button class="order-action storno-action" data-storno="${esc(o.id)}">Storner</button></div></article>`}).join("");document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>startEdit(b.dataset.edit));document.querySelectorAll("[data-storno]").forEach(b=>b.onclick=()=>stornOrder(b.dataset.storno))}
async function loadUt(){$("refresh").disabled=true;setConnection("ut","UT-database…");try{orders=await request("ut_orders?select=*&order=created_at.desc&limit=100")||[];renderHistory();setConnection("ut",`UT tilkoblet · ${activeOrders().length} aktive`,"ok")}catch(e){$("history").innerHTML='<div class="empty">UT-databasen kunne ikke lastes.</div>';$("historyCount").textContent="Feil";setConnection("ut","UT-feil","bad",`Feil ved lesing av ut_orders:\n${e.message||e}`)}finally{$("refresh").disabled=false}}
function startEdit(id){const o=orders.find(x=>String(x.id)===String(id));if(!o||o.status!=="new")return msg("Bare oppdrag med status Ny kan redigeres.","bad");const p=singleProduct(o);if(!p)return msg("Et kombinert oppdrag kan ikke redigeres i denne enkle formen.","bad");editingId=o.id;$("ramp").value=o.ramp||"";$("officeNote").value=o.office_note||"";if(p==="bunner"){state={product:p,mode:"stacks",stacks:+o.bunner_stacks||1,total:(+o.bunner_stacks||1)*10,direct:1};$("qty").value=state.stacks}else{state={product:p,mode:"stacks",stacks:1,total:10,direct:p==="hyller30"?(+o.hyller30_sets||1):(+o.hyller60_sets||1)};$("directQty").value=state.direct}product(p);mode(state.mode);$("formTitle").textContent="Rediger UT-bestilling";$("editBanner").textContent=`Redigerer ${o.order_number||o.id}. Bare status Ny kan lagres.`;$("editBanner").classList.add("show");$("send").textContent="Lagre endringer";$("reset").textContent="Avbryt redigering";$("receipt").classList.remove("show");msg("");$("formCard").scrollIntoView({behavior:"smooth",block:"start"})}
async function stornOrder(id){const o=orders.find(x=>String(x.id)===String(id));if(!o||["completed","cancelled"].includes(o.status))return;const reason=prompt(`Hvorfor skal ${o.order_number||"oppdraget"} storneres?`,`Stornert fra kontoret.`);if(reason===null)return;if(!confirm(`Storner oppdraget til rampe ${o.ramp}?`))return;try{msg("Stornerer oppdrag…");await request("rpc/cancel_ut_order",{method:"POST",body:JSON.stringify({p_order_id:o.id,p_reason:reason.trim()||"Stornert fra kontoret."})});if(String(editingId)===String(id))clearForm(false);msg("Oppdraget er stornert. Det er beholdt i databasen, men fjernet fra arbeidslisten.","ok");await Promise.all([loadInn(),loadUt()])}catch(e){msg(`Kunne ikke stornere oppdraget.\n${e.message||e}`,"bad")}}
function clearForm(focus=true){editingId=null;state={product:"bunner",mode:"stacks",stacks:1,total:10,direct:1};$("ramp").value="";$("officeNote").value="";$("qty").value=1;$("directQty").value=1;$("receipt").classList.remove("show");$("formTitle").textContent="Ny UT-bestilling";$("editBanner").classList.remove("show");$("editBanner").textContent="";$("send").textContent="Send UT-oppdrag";$("reset").textContent="Nullstill";product("bunner");mode("stacks");msg("");if(focus)$("ramp").focus()}
$("ramp").oninput=()=>{$("ramp").value=$("ramp").value.replace(/[^0-9A-Za-z-]/g,"");render()};document.querySelectorAll("[data-product]").forEach(b=>b.onclick=()=>product(b.dataset.product));document.querySelectorAll("[data-mode]").forEach(b=>b.onclick=()=>mode(b.dataset.mode));$("qty").oninput=updateQty;$("qty").onchange=updateQty;$("directQty").oninput=()=>{state.direct=pos($("directQty").value);$("directQty").value=state.direct;render()};$("minus").onclick=()=>{state.mode==="stacks"?(state.stacks=Math.max(1,state.stacks-1),state.total=state.stacks*10,$("qty").value=state.stacks):(state.total=Math.max(10,state.total-10),state.stacks=state.total/10,$("qty").value=state.total);render()};$("plus").onclick=()=>{state.mode==="stacks"?(state.stacks++,state.total=state.stacks*10,$("qty").value=state.stacks):(state.total+=10,state.stacks=state.total/10,$("qty").value=state.total);render()};$("dMinus").onclick=()=>{state.direct=Math.max(1,state.direct-1);$("directQty").value=state.direct;render()};$("dPlus").onclick=()=>{state.direct++;$("directQty").value=state.direct;render()};document.querySelectorAll("#dQuick [data-v]").forEach(b=>b.onclick=()=>{state.direct=pos(b.dataset.v);$("directQty").value=state.direct;render()});$("send").onclick=send;$("reset").onclick=()=>clearForm();$("refresh").onclick=()=>Promise.all([loadInn(),loadUt()]);quick();render();Promise.all([loadInn(),loadUt()]);setInterval(()=>{if(!document.hidden)Promise.all([loadInn(),loadUt()])},10000);
